### ISSUE TITLE
Adding search page structure

### ISSUE THREAD

**Issue by tnleang** [5-Star-Users/CS4800Fall19#1]
The search page will allows students to search through their choice of professors' office hour.
 Requirements:
      - it should take at least a professor's name
      - it should not give an error when not found a result (simply return message)
      - it should not let students to search with an empty key

**Comment by haohuynh** [comment]
Template for Edit is created. Please update the repository for the latest changes.

**Comment by haohuynh** [comment]
Template for Search is created. Please check the latest repository.

**Comment by haohuynh** [comment]
For simplicity, the Search criteria for beginning should include only: a faculty's firstName, lastName, departmentName, and courseNumber.

**Comment by haohuynh** [comment]
listFaculty() in the ModelController, supporting the search task, is submitted.

**Comment by haohuynh** [comment]
Code Submitted.
