### ISSUE TITLE
Adding log in page

### ISSUE THREAD

**Issue by tnleang** [5-Star-Users/CS4800Fall19#2]
Log in page only is only for staffs to use. This page does not allow users to modify anythings. It simply is the router for authorized users to the modifiable page.
Requirements:
    - it should have user and password inputs session
    - it should route users to the page where they can modify the data inside
    - it should only route users if they have authority to modify
    - it should denial unknown users (Notice: Students use this service as a guess. They do not need to log in)

**Comment by haohuynh** [comment]
Login page is created.

**Post condition:** 

Tomcat must be configured for https. Guideline: https://dzone.com/articles/setting-ssl-tomcat-5-minutes
Faculty table got changed to contain the hashed passphrase. Please check in mysql folder for the latest dump file.
