### ISSUE TITLE
MySQL Command Line Issue

### ISSUE THREAD

**Issue by haohuynh** [5-Star-Users/CS4800Fall19#3]
"Load Data Local Infile" is not supported by default on Windows and Mac systems. Thus, some members are unable to push raw data down to database OfficeHours . Alternative way: to export the current database to an sql file, and have mySQL servers imported that file.

**Comment by tnleang** [comment]
Added sql data file inside mysql directory. Hope it helps

**Comment by poudyalsaroz** [comment]
Commands in sql data file were run in MySQL and was able to add information in each tables.

**Comment by haohuynh** [comment]
mySQLdump solves the problem.
